# **Atelier Préparation de Données Tabulaires**

## **Objectifs Pédagogiques**

```
À la fin de l'atelier, l'apprenant doit être capable de :
1) explorer un jeu de données tabulaire ;
2) identifier les différents types de variables ;
3) détecter les problèmes de qualité ;
4) analyser les valeurs manquantes ;
5) détecter et traiter les doublons ;
6) identifier les valeurs aberrantes ;
7) détecter les incohérences ;
8) analyser le déséquilibre des classes ;
9) choisir une stratégie d'encodage adaptée ;
10) appliquer différents encodages catégoriels ;
11) normaliser et standardiser les variables numériques ;
12) éviter la fuite de données ;
13) construire un pipeline de preprocessing avec Scikit-learn ;
14) produire un dataset final exploitable par un algorithme de Machine Learning.
```

## **Partie 1 – Explorer les données**

### **1.1 Chargement des données CSV**

In [163]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [164]:
df = pd.read_csv('../data/smart_building_raw.csv', parse_dates=['date'], date_format="%Y-%m-%d %H:%M:%S" )

### **1.2 Affichage des premières lignes du dataset**

In [165]:
df.head()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
0,1174,2025-02-13 06:00:00,B8,Entrepôt,A,23.0,40.0,851.0,26.0,138.4,Eco,Normal,Jeudi,Non
1,1275,2025-03-10 12:00:00,B7,Bureau,D,28.0,69.0,538.0,0.0,170.2,Eco,Normal,Lundi,Non
2,1493,2025-05-04 00:00:00,B5,Centre commercial,B,19.5,52.3,1198.0,64.0,149.8,Normal,Normal,Dimanche,Oui
3,1073,2025-01-19 00:00:00,B6,Université,D,20.0,58.4,1014.0,30.0,141.6,Normal,Normal,Dimanche,Non
4,1454,2025-04-24 06:00:00,B7,Bureau,D,26.8,70.5,628.0,42.0,228.3,Normal,Normal,Jeudi,Non

### **1.3 Affichage des dernières lignes du dataset**

In [166]:
df.tail()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
502,1107,2025-01-27 12:00:00,B2,École,C,29.8,66.5,778.0,48.0,243.5,Normal,Normal,Lundi,Non
503,1271,2025-03-09 12:00:00,B3,Hôpital,B,21.1,66.3,3900.0,53.0,145.8,Eco,Alerte,Dimanche,Oui
504,1349,2025-03-29 00:00:00,B5,Centre commercial,B,21.6,61.9,959.0,33.0,100.2,Eco,Normal,Samedi,Non
505,1436,2025-04-19 18:00:00,B7,Bureau,C,21.2,54.5,1066.0,38.0,150.9,Boost,Normal,Samedi,Oui
506,1103,2025-01-26 12:00:00,B2,École,D,NaN,64.8,584.0,29.0,163.4,Normal,Panne,Dimanche,Non

### **1.4 Combien d'observations contient le dataset ?**

In [167]:
print(f"Le dataset contient {df.shape[0]} onservations")

Le dataset contient 507 onservations

### **1.5 Combien de variables possède le dataset ?**

In [168]:
print(f"Le dataset contient {df.shape[1]} variables (colonnes)")

Le dataset contient 14 variables (colonnes)

### **1.6 Les variables numériques**

In [169]:
print(f"Les variables numériques: \n {df.select_dtypes(include='number').columns.values}")

Les variables numériques:
 <StringArray>
['id_mesure', 'temperature', 'humidite', 'co2', 'occupation',
 'consommation_kwh']
Length: 6, dtype: str

### **1.7 Les variables catégorielles**

In [170]:
print(f"Les variables numériques: \n {df.select_dtypes(exclude=['number', 'datetime']).columns.values}")

Les variables numériques:
 <StringArray>
[              'date',           'batiment',      'type_batiment',
               'zone', 'mode_climatisation',       'etat_systeme',
       'jour_semaine',             'alerte']
Length: 8, dtype: str

### **1.8 Indentifier Les dates**

In [171]:
df['date'] = pd.to_datetime(df['date'], errors="coerce")

In [172]:
print(f"Les variables numériques: \n {df.select_dtypes(include='datetime').columns.values}")

Les variables numériques:
 <StringArray>
['date']
Length: 1, dtype: str

### **1.9 Identification des identifiants**

In [173]:
df['id_mesure']

0      1174
1      1275
2      1493
3      1073
4      1454
       ...
502    1107
503    1271
504    1349
505    1436
506    1103
Name: id_mesure, Length: 507, dtype: int64

### **1.10 Les statistiques : moyenne, médiane, minimum, maximum, écart-type et quartiles**

In [174]:
df.describe()

,id_mesure,date,temperature,humidite,co2,occupation,consommation_kwh
count,507.000000,502,495.000000,496.000000,500.000000,501.000000,502.000000
mean,1251.114398,2025-03-04 13:26:03.346613,24.154141,57.864113,844.150000,44.850299,169.069323
min,1001.000000,2025-01-01 00:00:00,-30.000000,-12.000000,89.000000,-20.000000,-100.000000
25%,1125.500000,2025-02-01 01:30:00,21.600000,49.275000,623.750000,27.000000,136.875000
50%,1252.000000,2025-03-04 21:00:00,24.000000,57.550000,787.500000,46.000000,169.800000
75%,1376.500000,2025-04-04 22:30:00,26.000000,65.750000,952.000000,61.000000,202.975000
max,1500.000000,2025-05-05 18:00:00,96.000000,160.000000,6000.000000,116.000000,336.200000
std,144.782769,NaN,7.418465,16.026336,582.181386,24.949139,53.164294

### **1.11 Y a-t-il des variables potentiellement problématiques ?**

In [175]:
df.describe()

,id_mesure,date,temperature,humidite,co2,occupation,consommation_kwh
count,507.000000,502,495.000000,496.000000,500.000000,501.000000,502.000000
mean,1251.114398,2025-03-04 13:26:03.346613,24.154141,57.864113,844.150000,44.850299,169.069323
min,1001.000000,2025-01-01 00:00:00,-30.000000,-12.000000,89.000000,-20.000000,-100.000000
25%,1125.500000,2025-02-01 01:30:00,21.600000,49.275000,623.750000,27.000000,136.875000
50%,1252.000000,2025-03-04 21:00:00,24.000000,57.550000,787.500000,46.000000,169.800000
75%,1376.500000,2025-04-04 22:30:00,26.000000,65.750000,952.000000,61.000000,202.975000
max,1500.000000,2025-05-05 18:00:00,96.000000,160.000000,6000.000000,116.000000,336.200000
std,144.782769,NaN,7.418465,16.026336,582.181386,24.949139,53.164294

```
On observe que la colonne temperature, co2, humidite, occupation presente des valeur aberantes qu'il faut gèrer,

Les variables catégoriels aussi doivent être vérifier
```

In [176]:
df.isna().sum()

id_mesure              0
date                   5
batiment               0
type_batiment          4
zone                   0
temperature           12
humidite              11
co2                    7
occupation             6
consommation_kwh       5
mode_climatisation     5
etat_systeme           0
jour_semaine           5
alerte                 0
dtype: int64

In [177]:
df['id_mesure'].duplicated().sum()

np.int64(7)

### **1.12 Pour les données incohérentes :**

#### **a. recherche des valeurs telles que humidité < 0 ;**

In [178]:
df[df['humidite'] < 0]['humidite']

281    -5.0
335    -8.0
366   -12.0
Name: humidite, dtype: float64

#### **b. rechercher des valeurs telles que humidité > 100 ;**

In [179]:
df[df['humidite'] > 100]['humidite']

59     108.0
103    145.0
128    160.0
160    125.0
268    140.0
327    132.0
342    110.0
Name: humidite, dtype: float64

#### **c. recherche des valeurs telles que température extrêmement élevée ;**

In [180]:
df.describe()

,id_mesure,date,temperature,humidite,co2,occupation,consommation_kwh
count,507.000000,502,495.000000,496.000000,500.000000,501.000000,502.000000
mean,1251.114398,2025-03-04 13:26:03.346613,24.154141,57.864113,844.150000,44.850299,169.069323
min,1001.000000,2025-01-01 00:00:00,-30.000000,-12.000000,89.000000,-20.000000,-100.000000
25%,1125.500000,2025-02-01 01:30:00,21.600000,49.275000,623.750000,27.000000,136.875000
50%,1252.000000,2025-03-04 21:00:00,24.000000,57.550000,787.500000,46.000000,169.800000
75%,1376.500000,2025-04-04 22:30:00,26.000000,65.750000,952.000000,61.000000,202.975000
max,1500.000000,2025-05-05 18:00:00,96.000000,160.000000,6000.000000,116.000000,336.200000
std,144.782769,NaN,7.418465,16.026336,582.181386,24.949139,53.164294

In [181]:
q1, q3 = df['temperature'].quantile([.25, .75])
IQR = q3 - q1
df[df['temperature'] > q3 + 1.5*IQR]['temperature']

7      72.5
116    96.0
157    34.2
161    88.0
499    95.2
Name: temperature, dtype: float64

#### **d. recherche des valeurs telles que négative ;**

In [182]:
df[df['temperature'] < 0]['temperature']

185   -25.0
358   -30.0
Name: temperature, dtype: float64

#### **e. rechercher des valeurs telles que consommation négative ;**

In [183]:
df[df['consommation_kwh'] < 0]['consommation_kwh']

59     -15.0
154    -50.0
199    -20.0
441   -100.0
Name: consommation_kwh, dtype: float64

#### **f. Si une valeur est manifestement erronée et qu’on ne peut pas retrouver sa vraie valeur, la transformer en valeur manquante**

In [184]:
df.head()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
0,1174,2025-02-13 06:00:00,B8,Entrepôt,A,23.0,40.0,851.0,26.0,138.4,Eco,Normal,Jeudi,Non
1,1275,2025-03-10 12:00:00,B7,Bureau,D,28.0,69.0,538.0,0.0,170.2,Eco,Normal,Lundi,Non
2,1493,2025-05-04 00:00:00,B5,Centre commercial,B,19.5,52.3,1198.0,64.0,149.8,Normal,Normal,Dimanche,Oui
3,1073,2025-01-19 00:00:00,B6,Université,D,20.0,58.4,1014.0,30.0,141.6,Normal,Normal,Dimanche,Non
4,1454,2025-04-24 06:00:00,B7,Bureau,D,26.8,70.5,628.0,42.0,228.3,Normal,Normal,Jeudi,Non

#### **g. recherche des valeurs telles que catégories mal orthographiées**

In [185]:
for c in df.select_dtypes(exclude=['number', 'datetime']).columns.values.tolist():
     print(f"{c}: {df[c].unique().tolist()}")

batiment: ['B8', 'B7', 'B5', 'B6', 'B3', 'B4', 'B2', 'B1']
type_batiment: ['Entrepôt', 'Bureau', 'Centre commercial', 'Université', 'Hôpital', 'École', 'ÉCOLE', 'ecole', 'BUREAU', nan, 'Bureu', 'bureau', ' UNIVERSITÉ', 'hôpital ', 'centre commercial', ' Bureau ', 'entrepot']
zone: ['A', 'D', 'B', 'C']
mode_climatisation: ['Eco', 'Normal', 'Boost', nan, 'normal', 'BOOST', 'normale', 'Normal ']
etat_systeme: ['Normal', 'Alerte', 'Panne']
jour_semaine: ['Jeudi', 'Lundi', 'Dimanche', 'Vendredi', 'Mercredi', 'Mardi', 'Samedi', nan]
alerte: ['Non', 'Oui']

### **h. On normalise les catégories textuelles en supprimant les espaces puis en uniformisant la casse**

In [186]:
# Colonne jour_semaine
df["jour_semaine"] = df["jour_semaine"].str.strip().str.lower()
df['alerte'] = df['alerte'].str.lower()
df['etat_systeme'] = df['etat_systeme'].str.strip().str.lower()
df['batiment'] = df['batiment'].str.strip().str.lower()
df['zone'] = df['zone'].str.strip().str.lower()

In [187]:
df['type_batiment'] = (df['type_batiment'].str.strip().str.lower()
    .replace({'bureu': 'bureau', 'ecole': 'école', 'entrepot': 'entrepôt'}))

df['mode_climatisation'] = (df['mode_climatisation'].str.strip().str.lower()
    .replace({'normale': 'normal'}))

In [188]:
# VERIFICATION
for c in df.select_dtypes(exclude=['number', 'datetime']).columns.values.tolist():
     print(f"{c}: {df[c].unique().tolist()}")

batiment: ['b8', 'b7', 'b5', 'b6', 'b3', 'b4', 'b2', 'b1']
type_batiment: ['entrepôt', 'bureau', 'centre commercial', 'université', 'hôpital', 'école', nan]
zone: ['a', 'd', 'b', 'c']
mode_climatisation: ['eco', 'normal', 'boost', nan]
etat_systeme: ['normal', 'alerte', 'panne']
jour_semaine: ['jeudi', 'lundi', 'dimanche', 'vendredi', 'mercredi', 'mardi', 'samedi', nan]
alerte: ['non', 'oui']

### **13. Pour les valeurs manquantes :**

#### **a. Calcule du nombre et le pourcentage de valeurs manquantes par colonne**

In [ ]:
# Somme des valeurs manquantes de chaque colonne
df.isna().sum()

id_mesure              0
date                   5
batiment               0
type_batiment          4
zone                   0
temperature           12
humidite              11
co2                    7
occupation             6
consommation_kwh       5
mode_climatisation     5
etat_systeme           0
jour_semaine           5
alerte                 0
dtype: int64

In [ ]:
# Pourcentage des valeurs manquantes de chaque colonnes
(df.isna().mean() * 100).round(2)

id_mesure             0.00
date                  0.99
batiment              0.00
type_batiment         0.79
zone                  0.00
temperature           2.37
humidite              2.17
co2                   1.38
occupation            1.18
consommation_kwh      0.99
mode_climatisation    0.99
etat_systeme          0.00
jour_semaine          0.99
alerte                0.00
dtype: float64

#### **b. Quelle variable possède le plus de valeurs manquantes ?**

In [197]:
df.isna().sum().idxmax()

'temperature'

#### **c. Quelle stratégie utiliser pour les valeurs manquantes ?**

In [202]:
print(f"Temp min: {df['temperature'].min()}")
print(f"Temp max: {df['temperature'].max()}")
print(f"Ecart type: {df['temperature'].std()}")
print(f"Temp moyenne: {df['temperature'].mean()}")

Temp min: -30.0
Temp max: 96.0
Ecart type: 7.418464900364311
Temp moyenne: 24.154141414141414

On observe un grand ecart entre la temperature min et la temp max, de plus l'a moyenne et l'ecart-type sont éloignés ce qui sous entend la presence de valeurs aberantes. Donc on remplace les valeurs manquantes par la **medianne** qui est moins sensible aux outliers

#### **Peut-on supprimer toutes les lignes contenant des valeurs manquantes ?**

In [209]:
taux = ((df.isna().sum().sum() / df.shape[0]) * 100).round(2)
print(taux)

11.83

Le taux de valeur manquante est superieur à 10%; pourle pas courrir le risque de perte d'information on peux les conserver et les remplacer par la medianne.